'use strict';
const $ = (s, el=document) => el.querySelector(s);
const esc = v => String(v ?? '').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt = v => v ? new Date(v).toLocaleString(undefined,{dateStyle:'medium',timeStyle:'short'}) : 'Not collected yet';
let user, page='instances', offset=0, records=[], groups=[], users=[], memberships=[], query='', state='', region='', renderID=0;
let cloudAccounts=[], selectedAccount=null, edsRegion='';
let edsRegions=[], edsQuery='', edsState='', edsBilling='', edsSort='name', edsDirection='asc';
let edsAllDesktops=[], edsFailedRegions=[], edsAssignmentsError='', edsUserQuery='', edsUserStatus='', edsUserAdmin='', edsUserSort='id', edsUserDirection='asc';
let edsCreateCatalog=null;
const names={instances:'Overview',eds:'EDS desktops',edsusers:'EDS users',accounts:'Cloud connections',groups:'Access policies',users:'Team members',activity:'Audit log',settings:'Workspace settings',api:'API reference'};
const actionIcons={
 start:'<svg viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path d="M8 5.5v13l10-6.5z" fill="currentColor"/></svg>',
 stop:'<svg viewBox="0 0 24 24" aria-hidden="true" focusable="false"><rect x="6" y="6" width="12" height="12" rx="1.5" fill="currentColor"/></svg>',
 manage:'<svg viewBox="0 0 24 24" aria-hidden="true" focusable="false"><path d="M4 7h10M18 7h2M4 17h2M10 17h10M14 4v6M7 14v6" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"/><circle cx="14" cy="7" r="2" fill="currentColor"/><circle cx="7" cy="17" r="2" fill="currentColor"/></svg>'
};
async function api(path, options={}) {
 const response=await fetch('/api/v1'+path,{...options,headers:{'Content-Type':'application/json',...options.headers},credentials:'same-origin'});
 const data=await response.json();
 if(!response.ok){if(response.status===401 && path!='/auth/login') showLogin();throw new Error(data.error || 'Request failed');}return data;
}
const send=(path,method,body)=>api(path,{method,body:body===undefined?undefined:JSON.stringify(body)});
function toast(message){$('#toast').textContent=message;$('#toast').hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>$('#toast').hidden=true,5000);}
function showLogin(){$('#app').hidden=true;$('#login').hidden=false;$('#modal').close();user=null;cloudAccounts=[];selectedAccount=null;}
async function showApp(){$('#login').hidden=true;$('#app').hidden=false;$('#workspace-name').textContent=user.workspace;$('#profile-name').innerHTML=esc(user.username)+'<small>'+esc(user.is_owner?'Workspace owner':user.role==='admin'?'Administrator':'Workspace member')+'</small>';$('#avatar').textContent=user.username[0].toUpperCase();document.querySelectorAll('.admin-only').forEach(e=>e.hidden=user.role!=='admin');try{await initializeCloudContext();}catch(e){toast(e.message);}render();}
async function initializeCloudContext(){cloudAccounts=(await api('/accounts')).data;const saved=localStorage.getItem('nexus.account.'+user.id)||localStorage.getItem('ccmp.account.'+user.id);selectedAccount=cloudAccounts.find(a=>String(a.id)===saved)||null;syncAccountSelector();}
function syncAccountSelector(){const control=$('#account-context');control.innerHTML='<option value="">All accessible accounts</option>'+cloudAccounts.map(a=>`<option value="${a.id}" ${selectedAccount?.id===a.id?'selected':''}>${esc(a.name)} · ${a.provider==='alibaba'?'Alibaba':'AWS'}</option>`).join('');renderProviderNavigation();}
function renderProviderNavigation(){const provider=selectedAccount?.provider;$('#compute-nav-label').textContent=provider==='alibaba'?'ECS instances':provider==='aws'?'EC2 instances':'Overview';$('#provider-context').textContent=selectedAccount?(provider.toUpperCase()+' / '+selectedAccount.name.toUpperCase()):'MULTI-CLOUD OVERVIEW';$('#provider-navigation').innerHTML=provider==='alibaba'?'<a href="#eds" data-page="eds"><span>▣</span>EDS desktops</a><a href="#edsusers" data-page="edsusers"><span>◎</span>EDS users</a>':'';}
function heading(eyebrow,title,description,actions=''){return `<div class="heading"><div><span class="eyebrow">${eyebrow}</span><h1>${title}</h1><p>${description}</p></div><div class="heading-actions">${actions}</div></div>`;}
const button=(label,action,kind='primary',id='',region='')=>`<button class="${kind}" data-action="${action}" data-id="${esc(id)}"${region?` data-region="${esc(region)}"`:''}>${label}</button>`;
const iconButton=(icon,label,action,kind,id,region='')=>`<button type="button" class="${kind} table-icon-button" data-action="${action}" data-id="${esc(id)}"${region?` data-region="${esc(region)}"`:''} aria-label="${esc(label)}" title="${esc(label)}">${actionIcons[icon]}</button>`;
const badge=v=>`<span class="badge ${esc(v)}">${esc(v)}</span>`;
const empty=(title,description,action='')=>`<div class="empty"><div class="empty-icon">☁</div><h3>${title}</h3><p>${description}</p>${action}</div>`;
const stat=(label,value,note,icon='▦')=>`<div class="stat"><div class="stat-top">${label}<i>${icon}</i></div><strong class="stat-value">${value}</strong><small>${note}</small></div>`;
const pager=(count)=>`<div class="pagination"><span>${count ? `${offset+1}–${offset+count}`:'0'} results · 50 per page</span><div><button class="secondary" data-action="prev" ${offset===0?'disabled':''}>←</button><button class="secondary" data-action="next" ${count<50?'disabled':''}>→</button></div></div>`;
const table=(headers,rows)=>`<div class="table-wrap"><table><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.join('')}</tbody></table></div>`;
async function render(){
 if(!user)return;const id=++renderID;page=location.hash.slice(1).split('?')[0]||'instances';if(!names[page]||((page==='eds'||page==='edsusers')&&selectedAccount?.provider!=='alibaba'))page='instances';$('#breadcrumb').textContent=names[page];document.querySelectorAll('nav a').forEach(a=>a.classList.toggle('active',a.dataset.page===page));$('#content').innerHTML='<div class="loading">Loading workspace…</div>';
 try{let html='';if(page==='instances')html=await inventory();if(page==='eds')html=await edsDesktopsPage();if(page==='edsusers')html=await edsUsersPage();if(page==='accounts')html=await accountsPage();if(page==='groups')html=await groupsPage();if(page==='users')html=await usersPage();if(page==='activity')html=await activityPage();if(page==='settings')html=await settingsPage();if(page==='api')html=apiPage();if(id===renderID)$('#content').innerHTML=html;}catch(e){if(id===renderID)$('#content').innerHTML=empty('Unable to load this page',esc(e.message),button('Try again','reload','secondary'));}
}
async function inventory(){
 const p=new URLSearchParams({q:query,state,region,limit:'50',offset:String(offset)});if(selectedAccount)p.set('account_id',selectedAccount.id);
 const summaryParams=selectedAccount?'?account_id='+selectedAccount.id:'';
 const [items,summary]=await Promise.all([api('/instances?'+p),api('/summary'+summaryParams)]);records=items.data;
 const scope=selectedAccount?selectedAccount.name:'all accessible accounts';
 return heading('YOUR INFRASTRUCTURE, IN FOCUS',selectedAccount?(selectedAccount.provider==='alibaba'?'Alibaba ECS':'AWS EC2'):'Cloud overview',`Compute resources for ${esc(scope)}.`,`${button('↻ &nbsp; Refresh','reload','secondary')}${user.role==='admin'?button('Sync cloud ↗','sync'):''}`)+
 `<div class="hero"><div><span class="eyebrow">CONNECTED. ORGANIZED. UNDER CONTROL.</span><h2>A little clarity for your cloud.</h2><p>Track compute infrastructure across AWS and Alibaba Cloud from one isolated workspace.</p></div><div class="hero-art" aria-hidden="true"><span>☁</span><span>▦</span><span>⌘</span></div></div>`+
 `<div class="stat-grid">${stat('Total instances',summary.instances,'Across your accessible accounts')}${stat('Running',summary.running,'Instances currently online','◉')}${stat('Cloud accounts',summary.accounts,'Connected cloud accounts','☁')}${stat('Active regions',summary.regions,'Regions with discovered instances','◎')}</div>`+
 `<div class="panel"><div class="panel-heading"><div><h2>Compute inventory <span class="count">${summary.instances}</span></h2><p>Your cloud components, all in one place.</p></div><span class="muted">AWS EC2 · ALIBABA ECS</span></div><form id="filters" class="toolbar"><input name="q" aria-label="Search instances" placeholder="Search name, instance ID, IP, or account…" value="${esc(query)}"><select name="state" aria-label="Instance state"><option value="">All states</option>${['running','stopped','pending','starting','stopping','terminated'].map(s=>`<option ${s===state?'selected':''}>${s}</option>`).join('')}</select><input name="region" aria-label="Cloud region" placeholder="All regions" value="${esc(region)}"><button class="secondary">Filter</button></form>`+
 (records.length?table(['INSTANCE','STATUS','INSTANCE TYPE','REGION','ACCOUNT',''],records.map(i=>`<tr><td><strong>${esc(i.name||i.instance_id)}</strong><small>${esc(i.provider.toUpperCase())} · ${esc(i.instance_id)}</small></td><td>${badge(i.state)}</td><td>${esc(i.instance_type)}</td><td>${esc(i.region)}</td><td>${esc(i.account_name)}</td><td>${button('View ↗','details','text-button',i.id)}</td></tr>`)):empty(query||state||region?'No matching instances':'Your cloud starts here',query||state||region?'Try another search or clear your filters.':'Connect an AWS or Alibaba Cloud account, then sync to discover compute instances.',user.role==='admin'?button('Connect account ↗','add-account'):''))+pager(records.length)+'</div>';
}
function edsPath(resource,targetRegion=edsRegion){return `/accounts/${selectedAccount.id}/eds${resource}?region=${encodeURIComponent(targetRegion)}`;}
function preferredEDSRegion(){return selectedAccount?.regions?.[0]||selectedAccount?.discovered_regions?.[0]||'cn-hangzhou';}
const desktopRegion=d=>d.RegionId||edsRegion;
function edsRegionBar(allowAll=false){
 const selectedKnown=edsRegion==='all'||edsRegions.some(r=>r.id===edsRegion);
 const allOption=allowAll?`<option value="all" ${edsRegion==='all'?'selected':''}>All regions</option>`:'';
 const options=allOption+(selectedKnown?'':`<option value="${esc(edsRegion)}">${esc(edsRegion)} · selected</option>`)+edsRegions.map(r=>`<option value="${esc(r.id)}" ${r.id===edsRegion?'selected':''}>${esc(r.id)}${r.name?' · '+esc(r.name):''} — ${r.available?r.desktops+' desktop'+(r.desktops===1?'':'s'):'count unavailable'}</option>`).join('');
 const shortcuts=edsRegions.filter(r=>r.available&&r.desktops>0).map(r=>`<button type="button" class="region-shortcut ${r.id===edsRegion?'active':''}" data-action="eds-region" data-id="${esc(r.id)}" aria-pressed="${r.id===edsRegion}"><span>${esc(r.id)}</span><strong>${r.desktops}</strong></button>`).join('');
 return `<div class="toolbar provider-toolbar"><label class="region-select" for="eds-region-select">EDS region<select id="eds-region-select" required>${options}</select></label>${shortcuts?`<div class="region-shortcuts" aria-label="Regions with EDS desktops">${shortcuts}</div>`:''}</div>`;
}
function edsTableHTML(){
 const text=edsQuery.trim().toLowerCase();
 let items=records.filter(d=>(!text||[d.DesktopName,d.DesktopId,d.DesktopType,d.BundleName,d.PolicyGroupName,...(d.EndUserIds||[])].some(v=>String(v||'').toLowerCase().includes(text)))&&(!edsState||String(d.DesktopStatus||'').toLowerCase()===edsState)&&(!edsBilling||d.ChargeType===edsBilling));
 const key={name:d=>d.DesktopName||d.DesktopId,status:d=>d.DesktopStatus,type:d=>d.DesktopType||d.BundleName,billing:d=>d.ChargeType,expires:d=>d.ExpiredTime}[edsSort]||((d)=>d.DesktopName);
 items=[...items].sort((a,b)=>String(key(a)||'').localeCompare(String(key(b)||''),undefined,{numeric:true})*(edsDirection==='desc'?-1:1));
 const states=[...new Set(records.map(d=>String(d.DesktopStatus||'').toLowerCase()).filter(Boolean))].sort();
 const filters=`<form id="eds-filters" class="toolbar eds-toolbar"><input name="q" aria-label="Search EDS desktops" placeholder="Search name, ID, type, policy, or user…" value="${esc(edsQuery)}"><select name="state" aria-label="EDS desktop status"><option value="">All statuses</option>${states.map(s=>`<option value="${esc(s)}" ${s===edsState?'selected':''}>${esc(s)}</option>`).join('')}</select><select name="billing" aria-label="EDS billing method"><option value="">All billing</option><option value="PostPaid" ${edsBilling==='PostPaid'?'selected':''}>Pay-as-you-go</option><option value="PrePaid" ${edsBilling==='PrePaid'?'selected':''}>Subscription</option></select><select name="sort" aria-label="Sort EDS desktops"><option value="name" ${edsSort==='name'?'selected':''}>Sort: name</option><option value="status" ${edsSort==='status'?'selected':''}>Sort: status</option><option value="type" ${edsSort==='type'?'selected':''}>Sort: type</option><option value="billing" ${edsSort==='billing'?'selected':''}>Sort: billing</option><option value="expires" ${edsSort==='expires'?'selected':''}>Sort: expiry</option></select><select name="direction" aria-label="Sort direction"><option value="asc" ${edsDirection==='asc'?'selected':''}>Ascending</option><option value="desc" ${edsDirection==='desc'?'selected':''}>Descending</option></select><button class="secondary">Apply</button></form>`;
 const showRegion=edsRegion==='all';
 const rows=items.map(d=>{const status=String(d.DesktopStatus||'unknown').toLowerCase(),targetRegion=desktopRegion(d);const lifecycle=status==='running'?iconButton('stop','Stop desktop','eds-stop','danger',d.DesktopId,targetRegion):status==='stopped'?iconButton('start','Start desktop','eds-start','lifecycle-start',d.DesktopId,targetRegion):'';return `<tr><td><strong>${esc(d.DesktopName||d.DesktopId)}</strong><small>${esc(d.DesktopId)}</small></td><td><div class="status-control">${badge(status)}${lifecycle}</div></td><td><strong>${esc(d.DesktopType||d.BundleName||'—')}</strong><small>${esc(d.PolicyGroupName||'No policy name')}</small></td>${showRegion?`<td>${esc(targetRegion)}</td>`:''}<td>${esc(d.ChargeType||'—')}</td><td>${esc((d.EndUserIds||[]).join(', ')||'—')}</td><td>${esc(d.ExpiredTime||'—')}</td><td>${iconButton('manage','Manage desktop','eds-manage','manage-action',d.DesktopId,targetRegion)}</td></tr>`;});
 const warning=edsFailedRegions.length?`<div class="inline-warning">Some regions could not be loaded: ${esc(edsFailedRegions.join(', '))}</div>`:'';
 const headers=['DESKTOP','STATUS','TYPE / POLICY',...(showRegion?['REGION']:[]),'BILLING','USERS','EXPIRES',''];
 return `<div id="eds-table-panel" class="panel"><div class="panel-heading"><div><h2>Cloud desktops <span class="count">${items.length} / ${records.length}</span></h2><p>Live data from WUYING Elastic Desktop Service.</p></div><span class="muted">REGION · ${esc(edsRegion)}</span></div>${warning}${filters}${items.length?table(headers,rows):empty(records.length?'No matching desktops':showRegion?'No EDS desktops in any region':'No EDS desktops in this region',records.length?'Change or clear the table filters.':showRegion?'Select a specific region to create a desktop.':'Create a desktop or select another Alibaba region.',records.length||showRegion?'':button('+ Create desktop','eds-create'))}</div>`;
}
async function edsDesktopsPage(){
 if(!selectedAccount)return empty('Select an Alibaba account','Choose a cloud account from the sidebar.');
 edsRegion=edsRegion||preferredEDSRegion();
 let desktopResult;try{desktopResult=await api(edsPath('/desktops'));}catch(error){const actions=edsRegion==='all'?'':button('+ Create desktop','eds-create');const shell=heading('ALIBABA CLOUD / WUYING','EDS desktops',`Create and operate cloud desktops in ${esc(selectedAccount.name)}.`,actions)+edsRegionBar(true);return shell+`<div class="panel">${empty('Unable to load EDS',esc(error.message))}</div>`;}records=desktopResult.data;edsFailedRegions=desktopResult.failed_regions||[];try{edsRegions=(await api(`/accounts/${selectedAccount.id}/eds/regions`)).data;}catch{edsRegions=[...new Set([...(selectedAccount.regions||[]),...(selectedAccount.discovered_regions||[]),edsRegion].filter(id=>id&&id!=='all'))].sort().map(id=>({id,name:'',desktops:id===edsRegion?records.length:-1,available:id===edsRegion}))}if(edsRegion!=='all'){try{users=(await api(edsPath('/users'))).data;}catch{users=[];}}
 const actions=edsRegion==='all'?'<span class="muted">Select a region to create a desktop</span>':button('+ Create desktop','eds-create');
 return heading('ALIBABA CLOUD / WUYING','EDS desktops',`Create and operate cloud desktops in ${esc(selectedAccount.name)}.`,actions)+edsRegionBar(true)+edsTableHTML();
}
function userDesktopCount(userID){return edsAllDesktops.filter(d=>(d.EndUserIds||[]).includes(userID)).length;}
function edsUsersTableHTML(){
 const text=edsUserQuery.trim().toLowerCase();
 let items=records.filter(u=>(!text||[u.EndUserId,u.RealNickName,u.NickName,u.Email,u.WyId].some(v=>String(v||'').toLowerCase().includes(text)))&&(!edsUserStatus||String(u.Status??'unknown')===edsUserStatus)&&(!edsUserAdmin||(edsUserAdmin==='yes')===!!u.EnableAdminAccess));
 const key={id:u=>u.EndUserId,name:u=>u.RealNickName||u.NickName||u.EndUserId,email:u=>u.Email,status:u=>u.Status,desktops:u=>userDesktopCount(u.EndUserId)}[edsUserSort]||((u)=>u.EndUserId);
 items=[...items].sort((a,b)=>String(key(a)??'').localeCompare(String(key(b)??''),undefined,{numeric:true})*(edsUserDirection==='desc'?-1:1));
 const statuses=[...new Set(records.map(u=>String(u.Status??'unknown')))].sort();
 const filters=`<form id="eds-user-filters" class="toolbar eds-toolbar"><input name="q" aria-label="Search EDS users" placeholder="Search user ID, name, email, or WUYING ID…" value="${esc(edsUserQuery)}"><select name="status" aria-label="EDS user status"><option value="">All statuses</option>${statuses.map(s=>`<option value="${esc(s)}" ${s===edsUserStatus?'selected':''}>${esc(s)}</option>`).join('')}</select><select name="admin" aria-label="Local administrator access"><option value="">All access levels</option><option value="yes" ${edsUserAdmin==='yes'?'selected':''}>Local admin</option><option value="no" ${edsUserAdmin==='no'?'selected':''}>Standard user</option></select><select name="sort" aria-label="Sort EDS users"><option value="id" ${edsUserSort==='id'?'selected':''}>Sort: user ID</option><option value="name" ${edsUserSort==='name'?'selected':''}>Sort: display name</option><option value="email" ${edsUserSort==='email'?'selected':''}>Sort: email</option><option value="status" ${edsUserSort==='status'?'selected':''}>Sort: status</option><option value="desktops" ${edsUserSort==='desktops'?'selected':''}>Sort: desktops</option></select><select name="direction" aria-label="Sort direction"><option value="asc" ${edsUserDirection==='asc'?'selected':''}>Ascending</option><option value="desc" ${edsUserDirection==='desc'?'selected':''}>Descending</option></select><button class="secondary">Apply</button></form>`;
 const rows=items.map(u=>`<tr><td><strong>${esc(u.EndUserId)}</strong><small>${esc(u.WyId||'')}</small></td><td>${esc(u.RealNickName||u.NickName||'—')}</td><td>${esc(u.Email||'—')}</td><td>${badge(String(u.Status??'unknown'))}</td><td>${u.EnableAdminAccess?'Yes':'No'}</td><td>${button(String(userDesktopCount(u.EndUserId)),'eds-user-desktops','binding-count',u.EndUserId)}</td></tr>`);
 const warning=edsAssignmentsError?`<div class="inline-warning">${esc(edsAssignmentsError)}</div>`:edsFailedRegions.length?`<div class="inline-warning">Desktop assignments may be incomplete because these regions could not be loaded: ${esc(edsFailedRegions.join(', '))}</div>`:'';
 return `<div id="eds-users-table-panel" class="panel"><div class="panel-heading"><div><h2>Convenience accounts <span class="count">${items.length} / ${records.length}</span></h2><p>Users and desktop assignments across every EDS region.</p></div><span class="muted">WUYING DIRECTORY</span></div>${warning}${filters}${items.length?table(['USER ID','DISPLAY NAME','EMAIL','STATUS','LOCAL ADMIN','DESKTOPS'],rows):empty(records.length?'No matching users':'No EDS users yet',records.length?'Change or clear the table filters.':'Create a convenience account, then bind it to a desktop.',records.length?'':button('+ Create EDS user','eds-user-create'))}</div>`;
}
async function edsUsersPage(){
 if(!selectedAccount)return empty('Select an Alibaba account','Choose a cloud account from the sidebar.');
 if(!edsRegion||edsRegion==='all')edsRegion=preferredEDSRegion();
 if(!edsRegions.length){try{edsRegions=(await api(`/accounts/${selectedAccount.id}/eds/regions`)).data;}catch{edsRegions=[];}}
 const shell=heading('ALIBABA CLOUD / DIRECTORY','EDS users',`Convenience accounts for ${esc(selectedAccount.name)}.`,button('+ Create EDS user','eds-user-create'))+edsRegionBar();
 try{records=(await api(edsPath('/users'))).data;}catch(error){return shell+`<div class="panel">${empty('Unable to load EDS users',esc(error.message)+' Check the selected directory region and RAM permissions.')}</div>`;}
 try{const desktopResult=await api(edsPath('/desktops','all'));edsAllDesktops=desktopResult.data;edsFailedRegions=desktopResult.failed_regions||[];edsAssignmentsError='';}catch(error){edsAllDesktops=[];edsFailedRegions=[];edsAssignmentsError='Desktop assignments are unavailable: '+error.message;}
 return shell+edsUsersTableHTML();
}
async function edsCreateForm(){
 if(edsRegion==='all'){toast('Select a specific region before creating a desktop.');return;}
 const [catalog,userResult]=await Promise.all([api(edsPath('/catalog')),api(edsPath('/users'))]);users=userResult.data;
 edsCreateCatalog=catalog;
 const options=(items,value,label)=>items.map(item=>`<option value="${esc(item[value])}">${esc(item[label]||item[value])}</option>`).join('');
 const customReady=(catalog.desktop_types||[]).length&&(catalog.images||[]).length;
 modal('Create EDS desktop',`<form id="eds-desktop-form"><p class="cost-warning"><strong>This operation can create billable Alibaba Cloud resources.</strong><br>Review the billing mode and enable payment only when intended.</p><label>Desktop name<input name="name" required maxlength="64"></label><div class="split-form"><label>Office site<select name="office_site_id" required>${options(catalog.office_sites,'OfficeSiteId','Name')}</select></label><div class="bundle-field"><label>Desktop bundle<select name="bundle_id">${options(catalog.bundles,'BundleId','BundleName')}<option value="">Custom configuration</option></select></label><button type="button" class="secondary compact-action" data-action="eds-customize" ${customReady?'':'disabled'} title="${customReady?'Choose CPU, RAM, image and disks':'Custom catalog unavailable; update Alibaba RAM permissions'}">Customize</button></div></div><div id="custom-config-summary" class="custom-config-summary" hidden></div><input type="hidden" name="desktop_type"><input type="hidden" name="image_id"><input type="hidden" name="default_language"><input type="hidden" name="system_disk_size"><input type="hidden" name="data_disk_size"><div class="split-form"><label>Billing<select name="charge_type"><option value="PostPaid">Pay-as-you-go</option><option value="PrePaid">Subscription</option></select></label><label>Amount<input name="amount" type="number" min="1" max="10" value="1" required></label><label>Subscription period<input name="period" type="number" min="1" max="60" value="1"></label><label>Period unit<select name="period_unit"><option value="Month">Month</option><option value="Year">Year</option></select></label></div><label>Assign users now (optional)<select name="end_user_ids" multiple size="4">${options(users,'EndUserId','EndUserId')}</select></label><div class="split-form"><label>Hostname (optional)<input name="hostname" minlength="2" maxlength="15" pattern="[A-Za-z0-9](?:[A-Za-z0-9-]{0,13}[A-Za-z0-9])?" placeholder="desktop-01"></label><label>Security policy (optional)<select name="policy_group_id"><option value="">Use Alibaba default</option>${options(catalog.policy_groups,'PolicyGroupId','Name')}</select></label></div><label class="check"><input type="checkbox" name="auto_pay">Charge the Alibaba account automatically</label><label class="check"><input type="checkbox" name="auto_renew">Enable automatic renewal</label><label class="check confirm-check"><input type="checkbox" name="confirm_cost" required>I understand this request can incur charges</label><p id="form-error" class="error" role="alert"></p><div class="form-actions"><button type="button" class="secondary" data-action="close">Cancel</button><button type="submit" class="primary">Create desktop</button></div></form>`);
}
function customDesktopForm(){
 const types=(edsCreateCatalog?.desktop_types||[]).filter(t=>t.DesktopTypeId&&t.CpuCount&&t.MemorySize),images=(edsCreateCatalog?.images||[]).filter(i=>i.ImageId&&i.OsType);
 if(!types.length||!images.length){toast('Custom desktop options are unavailable. Check DescribeDesktopTypes and DescribeImages permissions.');return;}
 const unique=(items,key)=>[...new Set(items.map(item=>String(item[key])).filter(Boolean))].sort((a,b)=>Number(a)-Number(b)||a.localeCompare(b));
 const cpus=unique(types,'CpuCount'),oses=unique(images,'OsType');
 $('#custom-modal-body').innerHTML=`<form id="eds-custom-form"><p class="muted">CPU and RAM select an available Alibaba desktop type. Disk sizes are in GiB.</p><div class="split-form"><label>vCPU<select name="cpu">${cpus.map(v=>`<option>${esc(v)}</option>`).join('')}</select></label><label>RAM (MiB)<select name="memory"></select></label><label>Operating system<select name="os">${oses.map(v=>`<option>${esc(v)}</option>`).join('')}</select></label><label>Image<select name="image_id"></select></label><label>System disk<input name="system_disk_size" type="number" min="60" max="500" step="10" value="80" required></label><label>Language<select name="default_language"><option value="en-US">English</option><option value="zh-CN">Simplified Chinese</option><option value="zh-HK">Traditional Chinese</option><option value="ja-JP">Japanese</option></select></label></div><label class="check"><input id="custom-data-disk" name="add_data_disk" type="checkbox">Add data disk</label><label id="custom-data-disk-size" hidden>Data disk size (GiB)<input name="data_disk_size" type="number" min="40" max="2040" step="10" value="40"></label><div id="custom-type-summary" class="custom-type-summary"></div><p id="custom-form-error" class="error"></p><div class="form-actions"><button type="button" class="secondary" data-action="close-custom">Cancel</button><button type="submit" class="primary">Use configuration</button></div></form>`;
 syncCustomOptions('cpu');$('#custom-modal').showModal();
}
function syncCustomOptions(changed){
 const form=$('#eds-custom-form');if(!form)return;const types=edsCreateCatalog.desktop_types||[],images=edsCreateCatalog.images||[];
 if(changed==='cpu'){const current=form.memory.value,memories=[...new Set(types.filter(t=>String(t.CpuCount)===form.cpu.value).map(t=>String(t.MemorySize)))].sort((a,b)=>Number(a)-Number(b));form.memory.innerHTML=memories.map(v=>`<option ${v===current?'selected':''}>${esc(v)}</option>`).join('');}
 if(changed==='os'||!form.image_id.options.length){const current=form.image_id.value;form.image_id.innerHTML=images.filter(i=>String(i.OsType)===form.os.value).map(i=>`<option value="${esc(i.ImageId)}" ${i.ImageId===current?'selected':''}>${esc(i.Name||i.ImageId)} · ${esc(i.OsName||i.OsType)}</option>`).join('');}
 const type=types.find(t=>String(t.CpuCount)===form.cpu.value&&String(t.MemorySize)===form.memory.value);$('#custom-type-summary').textContent=type?`${type.DesktopTypeId} · ${type.CpuCount} vCPU · ${type.MemorySize} MiB RAM`:'No matching desktop type';
}
function edsManageForm(id,targetRegion=edsRegion){
 const d=records.find(item=>item.DesktopId===id&&desktopRegion(item)===targetRegion)||{DesktopId:id,EndUserIds:[]};
 const running=String(d.DesktopStatus||'').toLowerCase()==='running',command=running?button('Send remote command','eds-command','secondary',id,targetRegion):'<button type="button" class="secondary" disabled title="Start the desktop before sending a remote command">Send remote command</button>';
 modal(d.DesktopName||id,`<p>${badge(String(d.DesktopStatus||'unknown').toLowerCase())} <span class="muted">${esc(id)} · ${esc(targetRegion)}</span></p><dl class="detail-grid"><div><dt>POLICY</dt><dd>${esc(d.PolicyGroupName||d.PolicyGroupId||'—')}</dd></div><div><dt>BILLING</dt><dd>${esc(d.ChargeType||'—')}</dd></div><div><dt>USERS</dt><dd>${esc((d.EndUserIds||[]).join(', ')||'none')}</dd></div><div><dt>TYPE</dt><dd>${esc(d.DesktopType||d.BundleName||'—')}</dd></div></dl><div class="operation-grid">${button('Reboot','eds-reboot','secondary',id,targetRegion)}${button('Bind / revoke user','eds-bind','secondary',id,targetRegion)}${button('Change policy','eds-policy','secondary',id,targetRegion)}${button('Maintenance mode','eds-maintenance','secondary',id,targetRegion)}${command}${button('Switch billing method','eds-billing','secondary',id,targetRegion)}${d.ChargeType==='PrePaid'?button('Renew subscription','eds-renew','secondary',id,targetRegion):''}</div><p class="muted">Policy and billing changes require account management access. Remote commands are available only while the desktop is running.</p>`);
}
function edsRenewForm(id,targetRegion=edsRegion){modal('Renew EDS desktop',`<form id="eds-renew-form" data-id="${esc(id)}" data-region="${esc(targetRegion)}"><p class="cost-warning"><strong>Renewal can incur charges.</strong> AutoPay off creates an unpaid order; AutoPay on attempts payment.</p><div class="split-form"><label>Period<input name="period" type="number" min="1" max="60" value="1" required></label><label>Unit<select name="period_unit"><option value="Month">Month</option><option value="Year">Year</option></select></label></div><label class="check"><input type="checkbox" name="auto_pay">Pay the renewal order automatically</label><label class="check confirm-check"><input type="checkbox" name="confirm_cost" required>I understand this request can incur charges</label><p id="form-error" class="error"></p><div class="form-actions"><button type="button" class="secondary" data-action="close">Cancel</button><button class="primary">Submit renewal</button></div></form>`);}
async function edsBindForm(id,targetRegion=edsRegion){users=(await api(edsPath('/users',targetRegion))).data;const d=records.find(item=>item.DesktopId===id&&desktopRegion(item)===targetRegion)||{EndUserIds:[]};modal('Desktop user access',`<form id="eds-bind-form" data-id="${esc(id)}" data-region="${esc(targetRegion)}"><label>Operation<select name="operation"><option value="bind">Bind selected users</option><option value="revoke">Revoke selected users</option></select></label><label>EDS users<select name="end_user_ids" multiple size="6" required>${users.map(u=>`<option value="${esc(u.EndUserId)}" ${(d.EndUserIds||[]).includes(u.EndUserId)?'selected':''}>${esc(u.EndUserId)} · ${esc(u.Email||'')}</option>`).join('')}</select></label><p class="muted">Hold Ctrl/Cmd to select multiple users.</p>${formFooter()}</form>`);}
function edsUserForm(){modal('Create EDS user',`<form id="eds-user-create-form"><p class="muted">Creates an Alibaba WUYING convenience account. Use lowercase letters, numbers, and underscores for the user ID.</p><div class="split-form"><label>User ID<input name="username" pattern="[a-z0-9_]{3,24}" minlength="3" maxlength="24" required></label><label>Display name<input name="display_name" maxlength="64"></label></div><label>Email<input name="email" type="email" maxlength="254" required></label><label>Initial password (optional)<input name="password" type="password" minlength="8" maxlength="30" autocomplete="new-password"></label><label class="check"><input name="is_local_admin" type="checkbox">Grant local administrator access</label><p id="form-error" class="error"></p><div class="form-actions"><button type="button" class="secondary" data-action="close">Cancel</button><button class="primary">Create EDS user</button></div></form>`);}
async function edsPolicyForm(id,targetRegion=edsRegion){const catalog=await api(edsPath('/catalog',targetRegion));const d=records.find(item=>item.DesktopId===id&&desktopRegion(item)===targetRegion)||{};modal('Change desktop policy',`<form id="eds-policy-form" data-id="${esc(id)}" data-region="${esc(targetRegion)}"><p class="muted">Alibaba requires the desktop to be running before its policy can be changed.</p><label>Security policy<select name="policy_group_id" required>${catalog.policy_groups.map(p=>`<option value="${esc(p.PolicyGroupId)}" ${p.PolicyGroupId===d.PolicyGroupId?'selected':''}>${esc(p.Name||p.PolicyGroupId)}</option>`).join('')}</select></label>${formFooter()}</form>`);}
function edsMaintenanceForm(id,targetRegion=edsRegion){modal('Maintenance mode',`<form id="eds-maintenance-form" data-id="${esc(id)}" data-region="${esc(targetRegion)}"><p class="muted">Maintenance mode prevents end users from connecting to this desktop while administrative work is performed.</p><label>Mode<select name="mode"><option value="ENTER">Enter maintenance mode</option><option value="EXIT">Exit maintenance mode</option></select></label><p id="form-error" class="error"></p><div class="form-actions"><button type="button" class="secondary" data-action="close">Cancel</button><button class="primary">Apply mode</button></div></form>`);}
function edsCommandForm(id,targetRegion=edsRegion){modal('Send remote command',`<form id="eds-command-form" data-id="${esc(id)}" data-region="${esc(targetRegion)}"><p class="cost-warning"><strong>This runs code inside the selected cloud desktop.</strong><br>Review the command carefully. Alibaba supports PowerShell and Bat scripts for Windows EDS desktops.</p><label>Script type<select name="command_type"><option value="RunPowerShellScript">PowerShell</option><option value="RunBatScript">Windows Bat</option></select></label><label>Command<textarea name="command" maxlength="16384" rows="10" required spellcheck="false" placeholder="Get-ComputerInfo"></textarea></label><label>Timeout (seconds)<input name="timeout" type="number" min="10" max="86400" value="300" required></label><label class="check confirm-check"><input type="checkbox" name="confirm" required>I reviewed this command and authorize its execution</label><p id="form-error" class="error"></p><div class="form-actions"><button type="button" class="secondary" data-action="close">Cancel</button><button class="primary">Run command</button></div></form>`);}
function renderEDSCommandResult(result){
 const status=String(result.status||'Pending'),output=result.output||'',error=[result.error_code,result.error_info].filter(Boolean).join(' · '),waiting=!result.completed;
 $('#modal-body').innerHTML=`<div class="command-result"><div class="command-status">${badge(status.toLowerCase())}<span>${waiting?'Waiting for Alibaba Cloud Assistant…':'Command finished'}</span></div>${error?`<p class="error">${esc(error)}</p>`:''}<pre id="command-output">${esc(output||(waiting?'Output will appear here when the command completes.':'(No output returned.)'))}</pre>${result.dropped?`<p class="inline-warning">Alibaba truncated ${result.dropped} bytes from the output.</p>`:''}<div class="form-actions"><button type="button" class="secondary" data-action="close">Close</button><button type="button" class="primary" data-action="copy-command-output" ${output?'':'disabled'}>Copy output</button></div></div>`;
}
async function waitForEDSCommand(desktopID,targetRegion,invokeID,timeout){
 const deadline=Date.now()+(timeout+20)*1000;let result={status:'Pending',completed:false,output:''},failures=0;renderEDSCommandResult(result);
 while($('#modal').open&&Date.now()<deadline){await new Promise(resolve=>setTimeout(resolve,2000));try{result=await api(edsPath(`/desktops/${encodeURIComponent(desktopID)}/commands/${encodeURIComponent(invokeID)}`,targetRegion));failures=0;}catch(error){failures++;result={...result,error_info:`Could not read the command result (${failures}/3): ${error.message}`};if(failures>=3)throw error;}renderEDSCommandResult(result);if(result.completed)return;}
 if($('#modal').open&&!result.completed){result.status='Client timeout';result.completed=true;result.error_info='The command may still be running in Alibaba Cloud. Re-run only after checking its state.';renderEDSCommandResult(result);}
}
function edsBillingForm(id,targetRegion=edsRegion){const d=records.find(item=>item.DesktopId===id&&desktopRegion(item)===targetRegion)||{};const target=d.ChargeType==='PrePaid'?'PostPaid':'PrePaid';modal('Switch billing method',`<form id="eds-billing-form" data-id="${esc(id)}" data-region="${esc(targetRegion)}"><p class="cost-warning"><strong>Billing conversion can create an order, charge the account, or trigger refund rules.</strong><br>The desktop must be running or stopped and have no overdue balance.</p><label>New billing method<select name="charge_type"><option value="PrePaid" ${target==='PrePaid'?'selected':''}>Subscription</option><option value="PostPaid" ${target==='PostPaid'?'selected':''}>Pay-as-you-go</option></select></label><div class="split-form"><label>Subscription period<input name="period" type="number" min="1" max="6" value="1" required></label><label>Period unit<select name="period_unit"><option value="Month">Month</option><option value="Year">Year</option><option value="Week">Week</option></select></label></div><label class="check"><input type="checkbox" name="auto_pay">Pay a generated order automatically</label><label class="check confirm-check"><input type="checkbox" name="confirm_cost" required>I understand the billing and refund impact</label><p id="form-error" class="error"></p><div class="form-actions"><button type="button" class="secondary" data-action="close">Cancel</button><button class="primary">Switch billing</button></div></form>`);}
function edsUserDesktopsForm(userID){
 const userRecord=records.find(item=>item.EndUserId===userID)||{EndUserId:userID};
 const desktops=[...edsAllDesktops].sort((a,b)=>String(desktopRegion(a)).localeCompare(String(desktopRegion(b)))||String(a.DesktopName||a.DesktopId).localeCompare(String(b.DesktopName||b.DesktopId)));
 const assignment=(d,bound)=>`<div class="assignment-row"><div><strong>${esc(d.DesktopName||d.DesktopId)}</strong><small>${esc(d.DesktopId)} · ${esc(desktopRegion(d))}</small></div><div>${badge(String(d.DesktopStatus||'unknown').toLowerCase())}<button type="button" class="${bound?'danger':'secondary'}" data-action="${bound?'eds-user-unbind':'eds-user-bind'}" data-id="${esc(d.DesktopId)}" data-user="${esc(userID)}" data-region="${esc(desktopRegion(d))}">${bound?'Unbind':'Bind'}</button></div></div>`;
 const bound=desktops.filter(d=>(d.EndUserIds||[]).includes(userID)),available=desktops.filter(d=>!(d.EndUserIds||[]).includes(userID));
 const warning=edsAssignmentsError?`<div class="inline-warning">${esc(edsAssignmentsError)}</div>`:edsFailedRegions.length?`<div class="inline-warning">Some regions could not be loaded: ${esc(edsFailedRegions.join(', '))}</div>`:'';
 modal(`Desktop access · ${userRecord.RealNickName||userRecord.NickName||userID}`,`<p class="muted">Manage this user's desktop access across all Alibaba EDS regions.</p>${warning}<div class="assignment-summary"><span><strong>${bound.length}</strong> bound</span><span><strong>${available.length}</strong> available</span></div><h3>Bound desktops</h3><div class="assignment-list">${bound.length?bound.map(d=>assignment(d,true)).join(''):'<p class="muted">No desktops are currently bound.</p>'}</div><h3>Available desktops</h3><div class="assignment-list">${available.length?available.map(d=>assignment(d,false)).join(''):'<p class="muted">No other desktops are available.</p>'}</div>`);
}
async function accountsPage(){const [a,g,m]=await Promise.all([api('/accounts'),api('/groups'),api('/memberships')]);records=cloudAccounts=a.data;groups=g.data;memberships=m.data;if(selectedAccount&&!cloudAccounts.some(a=>a.id===selectedAccount.id))selectedAccount=null;syncAccountSelector();return heading('CONNECTIONS','Cloud connections','Connect cloud environments to your isolated source of truth.',canCreateAccount()?button('+ Connect cloud','add-account'):'')+(records.length?`<div class="cards">${records.map(a=>`<article class="account-card"><div class="provider"><span class="${esc(a.provider)}">${a.provider==='alibaba'?'Alibaba Cloud':'AWS'}</span>${badge(a.sync_error?'error':a.last_sync_at?'connected':'pending')}</div><h3>${esc(a.name)}</h3><p>${esc(a.owner||'No owner assigned')}</p><div class="account-meta"><div><small>INSTANCES</small><strong>${a.instance_count}</strong></div><div><small>ACCESS GROUP</small><strong>${esc(a.group_name||'Administrators only')}</strong></div><div><small>REGIONS</small><strong>${a.regions.length?esc(a.regions.join(', ')):'All enabled regions'}</strong></div><div><small>LAST SYNC</small><strong>${fmt(a.last_sync_at)}</strong></div></div>${a.sync_error?`<p class="error">${esc(a.sync_error)}</p>`:''}<div class="card-actions">${canManageAccount(a)?button('Edit connection','edit-account','text-button',a.id)+button('Disconnect','delete-account','text-button danger-text',a.id):'<span class="muted">Read-only connection</span>'}</div></article>`).join('')}</div>`:`<div class="panel">${empty('Connect your first cloud account','AWS EC2 and Alibaba Cloud ECS are available now.',canCreateAccount()?button('Connect cloud ↗','add-account'):'Ask a group manager to connect an account.')}</div>`);}
function canManageGroup(g,kind){return user.role==='admin'||memberships.some(m=>m.user_id===user.id&&m.group_id===g.id&&m.role==='manager')&&g[kind];}
function canManageAccount(a){return user.role==='admin'||groups.some(g=>g.id===a.group_id&&canManageGroup(g,'manage_cloud_accounts'));}
function canCreateAccount(){return user.role==='admin'||groups.some(g=>canManageGroup(g,'manage_cloud_accounts'));}
async function groupsPage(){const [g,m]=await Promise.all([api('/groups'),api('/memberships')]);records=groups=g.data;memberships=m.data;return heading('ACCESS CONTROL','Access groups','Give each team the right visibility and control.',user.role==='admin'?button('+ Create group','add-group'):'')+`<div class="panel">`+(groups.length?table(['GROUP','MEMBERS','POLICIES',''],groups.map(g=>`<tr><td><strong>${esc(g.name)}</strong><small>${esc(g.description)}</small></td><td>${g.member_count}</td><td>${g.view_dashboard?'View inventory · ':''}${g.manage_cloud_accounts?'Manage accounts · ':''}${g.manage_group_members?'Manage members':''}</td><td>${canManageGroup(g,'manage_group_members')?button('Members','members','text-button',g.id):''}${user.role==='admin'?button('Edit','edit-group','text-button',g.id)+button('Delete','delete-group','text-button danger-text',g.id):''}</td></tr>`)):empty('Make room for your team','Create a group, connect accounts, and assign people the right role.'))+'</div>';}
async function usersPage(){const [u,g,m]=await Promise.all([api('/users'),api('/groups'),api('/memberships')]);records=users=u.data;groups=g.data;memberships=m.data;const limit=users[0]?.user_limit||6;const action=users.length<limit?button('+ Add team member','add-user'):`<span class="muted">${users.length}/${limit} seats used</span>`;return heading('WORKSPACE DIRECTORY','Team members',`Invite up to five people and assign access through policies. ${users.length}/${limit} seats used.`,action)+`<div class="panel">`+table(['PERSON','WORKSPACE ROLE','ACCESS POLICIES','JOINED',''],users.map(u=>`<tr><td><strong>${esc(u.username)}</strong><small>${u.is_owner?'Workspace owner':'Member #'+u.id}</small></td><td>${badge(u.role)}</td><td>${esc(memberships.filter(m=>m.user_id===u.id).map(m=>m.group_name+' / '+m.role).join(', ')||'—')}</td><td>${fmt(u.created_at)}</td><td>${button('Edit','edit-user','text-button',u.id)}${!u.is_owner&&u.id!==user.id?button('Remove','delete-user','text-button danger-text',u.id):''}</td></tr>`))+'</div>';
}
async function activityPage(){records=(await api('/activity?'+new URLSearchParams({q:query,limit:'50',offset:String(offset)}))).data;return heading('AUDIT TRAIL','Activity log','A record of changes across your workspace.',button('↻ Refresh','reload','secondary'))+`<div class="panel"><form class="toolbar" id="activity-filter"><label class="sr-label">Search activity<input name="q" placeholder="Action, username, or target…" value="${esc(query)}"></label><button class="secondary">Search</button></form>`+(records.length?table(['ACTION','PERFORMED BY','TARGET','TIME'],records.map(a=>`<tr><td><strong>${esc(a.action)}</strong><small>${esc(a.details?JSON.stringify(a.details):'')}</small></td><td>${esc(a.username)}</td><td>${esc(a.target||'—')}</td><td>${fmt(a.created_at)}</td></tr>`)):empty('No activity found','Workspace actions and collector runs will appear here.'))+pager(records.length)+'</div>';}
async function settingsPage(){const s=(await api('/settings')).data[0];return heading('PREFERENCES','Workspace settings','Keep your inventory current and your audit history useful.')+`<form id="settings-form" class="panel settings-card"><h2>Collection & retention</h2><p class="muted">The collector runs automatically for all connected accounts.</p><label>Collection interval (minutes)<input name="collector_interval_minutes" type="number" min="1" max="10080" required value="${s.collector_interval_minutes}"></label><label>Keep audit records for (days)<input name="audit_retention_days" type="number" min="7" max="3650" required value="${s.audit_retention_days}"></label><p class="muted">Last completed collection: ${fmt(s.last_collector_run_at)}</p><div class="form-actions">${button('Run collector now','sync','secondary')}<button class="primary" type="submit">Save settings</button></div></form>`;}
function apiPage(){return heading('BUILT TO CONNECT','API reference','The same capabilities as your portal, ready for your tools.')+`<div class="panel api-doc"><h2>One API. Your entire workspace.</h2><p class="muted">Base path: <code>/api/v1</code>. Send JSON requests. Resource access follows the same group permissions as the portal.</p><h3>Authenticate</h3><p class="muted">Log in to receive a bearer token valid for 12 hours. Keep it private. Logging out revokes it.</p><pre>curl -X POST '${esc(location.origin)}/api/v1/auth/login' \
  -H 'Content-Type: application/json' \
  -d '{"username":"YOUR_USERNAME","password":"YOUR_PASSWORD"}'

curl '${esc(location.origin)}/api/v1/instances?account_id=ACCOUNT_ID&state=running' \
	  -H 'Authorization: Bearer YOUR_TOKEN'</pre><h3>Endpoints</h3>${[['POST','/auth/signup','Create an isolated Community workspace'],['GET','/auth/me','Current user and workspace'],['POST','/auth/logout','Revoke current session'],['GET','/summary','Inventory counts · optional account_id'],['GET','/instances','Inventory · account_id, q, state, region, limit, offset'],['GET','/instances/{id}?live=true','Live security groups, disks and interfaces'],['POST','/instances/{id}/actions','Body: {"action":"start|stop|reboot"}'],['GET, POST','/accounts','List / connect cloud accounts'],['PUT, DELETE','/accounts/{id}','Update / disconnect an account'],['GET','/accounts/{id}/eds/regions','Supported EDS regions and desktop counts'],['GET, POST','/accounts/{id}/eds/desktops','List / create EDS desktops · region required'],['GET','/accounts/{id}/eds/catalog','Office sites, bundles and policies'],['POST','/accounts/{id}/eds/desktops/{desktopID}/actions','Start, stop or reboot EDS'],['POST','/accounts/{id}/eds/desktops/{desktopID}/renew','Renew prepaid EDS desktop'],['POST','/accounts/{id}/eds/desktops/{desktopID}/users','Bind or revoke EDS users'],['POST','/accounts/{id}/eds/desktops/{desktopID}/policy','Change EDS policy group'],['POST','/accounts/{id}/eds/desktops/{desktopID}/maintenance','Enter or exit maintenance mode'],['POST','/accounts/{id}/eds/desktops/{desktopID}/commands','Run a confirmed remote command'],['POST','/accounts/{id}/eds/desktops/{desktopID}/billing','Switch billing method · explicit confirmation'],['GET, POST','/accounts/{id}/eds/users','List / create EDS convenience users'],['GET, POST','/groups','List / create access groups'],['PUT, DELETE','/groups/{id}','Update / delete access groups'],['GET, POST','/users','List / create users · workspace admin'],['PUT, DELETE','/users/{id}','Update / delete users · workspace admin'],['GET','/memberships','List memberships'],['PUT, DELETE','/groups/{id}/members/{userID}','Assign / remove group membership'],['GET','/activity','Workspace audit log · admin · q, limit, offset'],['GET, PUT','/settings','Collector and retention settings · admin'],['POST','/collector/run','Queue this workspace collection · admin']].map(([method,path,desc])=>`<div class="api-row"><span class="api-method">${method}</span><div><code>${path}</code><p class="muted">${desc}</p></div></div>`).join('')}<h3>Responses & pagination</h3><p class="muted">Lists return <code>{"data": [...]}</code>. Default page size is 50, maximum 200. Use <code>offset</code> to advance. Errors return <code>{"error":"message"}</code> with an appropriate HTTP status. EDS requests are live, require an Alibaba account and region, and follow account permissions. See <code>docs/openapi.json</code> for request schemas.</p></div>`;}
function modal(title,body){$('#modal-title').textContent=title;$('#modal-body').innerHTML=body;$('#modal').showModal();}
function formFooter(){return '<p id="form-error" class="error" role="alert"></p><div class="form-actions"><button type="button" class="secondary" data-action="close">Cancel</button><button type="submit" class="primary">Save changes</button></div>';}
function accountForm(id){const a=records.find(a=>a.id===id)||{name:'',provider:'aws',owner:'',regions:[]};const permitted=groups.filter(g=>canManageGroup(g,'manage_cloud_accounts'));modal(id?'Edit cloud connection':'Connect cloud account',`<form id="account-form" data-id="${id||''}"><p class="muted">Credentials are encrypted at rest and never returned by the API.</p><div class="split-form"><label>Cloud provider<select name="provider"><option value="aws" ${a.provider==='aws'?'selected':''}>Amazon Web Services</option><option value="alibaba" ${a.provider==='alibaba'?'selected':''}>Alibaba Cloud</option></select></label><label>Account name<input name="name" required maxlength="100" value="${esc(a.name)}"></label></div><label>Owner<input name="owner" value="${esc(a.owner)}"></label><label>Access group<select name="group_id">${user.role==='admin'?'<option value="">Administrators only</option>':''}${permitted.map(g=>`<option value="${g.id}" ${g.id===a.group_id?'selected':''}>${esc(g.name)}</option>`).join('')}</select></label><label>Regions (comma separated; blank = all enabled)<input name="regions" placeholder="us-east-1 or cn-hangzhou, ap-southeast-1" value="${esc(a.regions.join(', '))}"></label><label>AccessKey ID ${id?'(leave credentials blank to keep existing)':''}<input name="access_key_id" autocomplete="off" ${id?'':'required'}></label><label>AccessKey secret<input name="secret_access_key" type="password" autocomplete="new-password" ${id?'':'required'}></label><label>STS security token (optional)<textarea name="session_token" autocomplete="off"></textarea></label>${formFooter()}</form>`);}
function groupForm(id){const g=groups.find(g=>g.id===id)||{view_dashboard:true};modal(id?'Edit access group':'Create access group',`<form id="group-form" data-id="${id||''}"><label>Group name<input name="name" required maxlength="100" value="${esc(g.name||'')}"></label><label>Description<textarea name="description">${esc(g.description||'')}</textarea></label>${[['view_dashboard','View instance inventory'],['manage_cloud_accounts','Allow group managers to manage cloud accounts'],['manage_group_members','Allow group managers to manage members']].map(([key,label])=>`<label class="check"><input type="checkbox" name="${key}" ${g[key]?'checked':''}>${label}</label>`).join('')}${formFooter()}</form>`);}
function userForm(id){const u=users.find(u=>u.id===id)||{};modal(id?'Edit person':'Add a person',`<form id="user-form" data-id="${id||''}"><label>Username<input name="username" minlength="3" maxlength="100" required value="${esc(u.username||'')}"></label><label>${id?'New password (blank keeps existing password)':'Password'}<input name="password" type="password" autocomplete="new-password" minlength="12" maxlength="72" ${id?'':'required'}></label><label>Workspace role<select name="role"><option value="user">User · permissions from groups</option><option value="admin" ${u.role==='admin'?'selected':''}>Administrator · full workspace access</option></select></label><p class="muted">Saving changes revokes this person's existing sessions.</p>${formFooter()}</form>`);}
async function membersForm(id){const g=groups.find(g=>g.id===id);if(user.role==='admin')users=(await api('/users')).data;const members=memberships.filter(m=>m.group_id===id);modal('Members · '+g.name,`${members.length?table(['PERSON','ROLE',''],members.map(m=>`<tr><td>${esc(m.username)}</td><td>${badge(m.role)}</td><td><button class="text-button danger-text" data-action="remove-member" data-id="${id}" data-user="${m.user_id}">Remove</button></td></tr>`)):'<p class="muted">No members yet.</p>'}<form id="member-form" data-id="${id}"><label>${user.role==='admin'?'Person':'User ID'}${user.role==='admin'?`<select name="user_id">${users.map(u=>`<option value="${u.id}">${esc(u.username)}</option>`).join('')}</select>`:'<input name="user_id" type="number" min="1" required>'}</label><label>Group role<select name="role"><option value="viewer">Viewer · inventory and details</option><option value="operator">Operator · viewer + instance actions</option><option value="manager">Manager · operator + group policies</option></select></label>${formFooter()}</form>`);}
async function details(id,live=false){const result=await api(`/instances/${id}${live?'?live=true':''}`);const i=result.instance;modal(i.name||i.instance_id,`<p>${badge(i.state)} <span class="muted">${esc(i.provider.toUpperCase())} · ${esc(i.instance_id)}</span></p><dl class="detail-grid">${Object.entries({'Instance type':i.instance_type,Region:i.region,'Public IP':i.public_ip||'—','Private IP':i.private_ip||'—','Last observed':fmt(i.seen_at),'VPC':i.details.vpc_id||'—','Subnet / vSwitch':i.details.subnet_id||'—','Launched':fmt(i.details.launch_time)}).map(([k,v])=>`<div><dt>${k}</dt><dd>${esc(v)}</dd></div>`).join('')}</dl><h3>Tags</h3><pre>${esc(JSON.stringify(i.details.tags||{},null,2))}</pre><div class="form-actions">${button('Live details','live-details','secondary',id)}${button('Start','start','secondary',id)}${button('Reboot','reboot','secondary',id)}${button('Stop','stop','danger',id)}</div><p class="muted">Instance actions require operator or manager access.</p>${result.live?`<h3>Live provider details</h3><pre>${esc(JSON.stringify(result.live,null,2))}</pre>`:''}`);}
async function performAction(action,id,el){
 if(action==='close')return $('#modal').close();if(action==='close-custom')return $('#custom-modal').close();if(action==='eds-customize')return customDesktopForm();if(action==='copy-command-output'){const output=$('#command-output')?.textContent||'';await navigator.clipboard.writeText(output);toast('Command output copied.');return;}if(action==='reload')return render();if(action==='prev'||action==='next'){offset=Math.max(0,offset+(action==='next'?50:-50));return render();}
 if(action==='eds-region')return selectEDSRegion(String(id));
 if(action==='sync'){await send('/collector/run','POST',{});toast('Collection queued. Refresh shortly to see updated inventory.');return;}
 const targetRegion=el?.dataset.region||edsRegion;
 if(action==='eds-create')return edsCreateForm();if(action==='eds-user-create')return edsUserForm();if(action==='eds-user-desktops')return edsUserDesktopsForm(String(id));if(action==='eds-manage')return edsManageForm(id,targetRegion);if(action==='eds-renew')return edsRenewForm(id,targetRegion);if(action==='eds-bind')return edsBindForm(id,targetRegion);if(action==='eds-policy')return edsPolicyForm(id,targetRegion);if(action==='eds-maintenance')return edsMaintenanceForm(id,targetRegion);if(action==='eds-command')return edsCommandForm(id,targetRegion);if(action==='eds-billing')return edsBillingForm(id,targetRegion);
 if(action==='eds-user-bind'||action==='eds-user-unbind'){const operation=action==='eds-user-bind'?'bind':'revoke',userID=el.dataset.user;if(operation==='revoke'&&!confirm(`Unbind ${userID} from this desktop?`))return;await send(edsPath('/desktops/'+encodeURIComponent(id)+'/users',targetRegion),'POST',{operation,end_user_ids:[userID]});const desktop=edsAllDesktops.find(d=>d.DesktopId===id&&desktopRegion(d)===targetRegion);if(desktop){const assigned=new Set(desktop.EndUserIds||[]);operation==='bind'?assigned.add(userID):assigned.delete(userID);desktop.EndUserIds=[...assigned];}const panel=$('#eds-users-table-panel');if(panel)panel.outerHTML=edsUsersTableHTML();toast(`Desktop access ${operation==='bind'?'granted':'revoked'}.`);return edsUserDesktopsForm(userID);}
 if(['eds-start','eds-stop','eds-reboot'].includes(action)){const operation=action.slice(4);if(!confirm(`${operation[0].toUpperCase()+operation.slice(1)} this EDS desktop? ${operation==='stop'?'Active user sessions may be interrupted.':''}`))return;await send(edsPath('/desktops/'+encodeURIComponent(id)+'/actions',targetRegion),'POST',{action:operation});toast(`Alibaba EDS accepted the ${operation} request.`);$('#modal').close();return render();}
 if(action==='add-account'){groups=(await api('/groups')).data;memberships=(await api('/memberships')).data;return accountForm();}if(action==='edit-account')return accountForm(id);
 if(action==='add-group'||action==='edit-group')return groupForm(id);if(action==='add-user'||action==='edit-user')return userForm(id);
 if(action==='members')return membersForm(id);if(action==='details'||action==='live-details')return details(id,action==='live-details');
 if(['start','stop','reboot'].includes(action)){if(!confirm(`${action[0].toUpperCase()+action.slice(1)} this compute instance? ${action==='stop'?'This will interrupt workloads.':''}`))return;await send(`/instances/${id}/actions`,'POST',{action});toast(`Cloud provider accepted the ${action} request.`);$('#modal').close();return render();}
 if(action==='remove-member'){if(!confirm('Remove this group membership?'))return;await send(`/groups/${id}/members/${el.dataset.user}`,'DELETE');memberships=(await api('/memberships')).data;$('#modal').close();await render();return membersForm(id);}
 const routes={'delete-account':'accounts','delete-group':'groups','delete-user':'users'};if(routes[action]){if(!confirm(action==='delete-account'?'Disconnect this account and remove its cached inventory? Cloud resources will remain untouched.':`Delete this ${action.slice(7)}?`))return;await send(`/${routes[action]}/${id}`,'DELETE');if(action==='delete-account')await initializeCloudContext();toast('Removed successfully.');return render();}
}
async function selectEDSRegion(nextRegion){
 nextRegion=String(nextRegion||'').trim();if(!nextRegion||nextRegion===edsRegion)return;edsRegion=nextRegion;edsQuery='';edsState='';edsBilling='';edsUserQuery='';edsUserStatus='';edsUserAdmin='';await render();
}
document.addEventListener('click',async e=>{const el=e.target.closest('[data-action]');if(!el)return;e.preventDefault();el.disabled=true;const raw=el.dataset.id;const id=el.dataset.action.startsWith('eds-')?raw||undefined:raw&&/^\d+$/.test(raw)?Number(raw):raw||undefined;try{await performAction(el.dataset.action,id,el);}catch(err){toast(err.message);}finally{el.disabled=false;}});
document.addEventListener('change',async e=>{
 if(e.target.id==='eds-region-select'){e.target.disabled=true;try{await selectEDSRegion(e.target.value);}catch(err){toast(err.message);}finally{e.target.disabled=false;}return;}
 const custom=e.target.closest('#eds-custom-form');
 if(custom){if(e.target.name==='cpu'||e.target.name==='os'||e.target.name==='memory')syncCustomOptions(e.target.name);if(e.target.name==='add_data_disk'){const field=$('#custom-data-disk-size');field.hidden=!e.target.checked;if(!e.target.checked)custom.data_disk_size.value='40';}return;}
 if(e.target.name==='bundle_id'&&e.target.closest('#eds-desktop-form')&&e.target.value){const form=e.target.form;for(const name of ['desktop_type','image_id','default_language','system_disk_size','data_disk_size'])form[name].value='';$('#custom-config-summary').hidden=true;}
});
document.addEventListener('submit',async e=>{
 const form=e.target;if(form.id==='login-form'||form.id==='signup-form')return;e.preventDefault();const data=Object.fromEntries(new FormData(form));const submit=$('[type=submit]',form)||$('button',form);if(submit)submit.disabled=true;
 try{if(form.id==='filters'){query=data.q;state=data.state;region=data.region;offset=0;return await render();}if(form.id==='activity-filter'){query=data.q;offset=0;return await render();}if(form.id==='eds-filters'){edsQuery=data.q;edsState=data.state;edsBilling=data.billing;edsSort=data.sort;edsDirection=data.direction;const panel=$('#eds-table-panel');if(panel)panel.outerHTML=edsTableHTML();return;}if(form.id==='eds-user-filters'){edsUserQuery=data.q;edsUserStatus=data.status;edsUserAdmin=data.admin;edsUserSort=data.sort;edsUserDirection=data.direction;const panel=$('#eds-users-table-panel');if(panel)panel.outerHTML=edsUsersTableHTML();return;}
 if(form.id==='eds-custom-form'){const types=edsCreateCatalog.desktop_types||[],type=types.find(t=>String(t.CpuCount)===data.cpu&&String(t.MemorySize)===data.memory),main=$('#eds-desktop-form');if(!type||!data.image_id)throw new Error('Select an available CPU/RAM type and image.');main.bundle_id.value='';main.desktop_type.value=type.DesktopTypeId;main.image_id.value=data.image_id;main.default_language.value=data.default_language;main.system_disk_size.value=data.system_disk_size;main.data_disk_size.value=data.add_data_disk?data.data_disk_size:'0';const summary=$('#custom-config-summary');summary.textContent=`Custom · ${data.cpu} vCPU · ${data.memory} MiB RAM · ${data.system_disk_size} GiB system disk${data.add_data_disk?` · ${data.data_disk_size} GiB data disk`:''}`;summary.hidden=false;$('#custom-modal').close();return;}
 if(form.id==='eds-desktop-form'){const fd=new FormData(form);if(!data.bundle_id&&!data.desktop_type)throw new Error('Choose a desktop bundle or complete the custom configuration.');await send(edsPath('/desktops'),'POST',{office_site_id:data.office_site_id,bundle_id:data.bundle_id,desktop_type:data.desktop_type,image_id:data.image_id,default_language:data.default_language,system_disk_size:Number(data.system_disk_size||0),data_disk_size:Number(data.data_disk_size||0),policy_group_id:data.policy_group_id,hostname:data.hostname,name:data.name,amount:Number(data.amount),charge_type:data.charge_type,period:Number(data.period),period_unit:data.period_unit,end_user_ids:fd.getAll('end_user_ids'),auto_pay:!!data.auto_pay,auto_renew:!!data.auto_renew,confirm_cost:!!data.confirm_cost});$('#modal').close();toast('EDS desktop creation was accepted.');return await render();}
 if(form.id==='eds-renew-form'){await send(edsPath('/desktops/'+encodeURIComponent(form.dataset.id)+'/renew',form.dataset.region),'POST',{period:Number(data.period),period_unit:data.period_unit,auto_pay:!!data.auto_pay,confirm_cost:!!data.confirm_cost});$('#modal').close();toast('EDS renewal request was accepted.');return await render();}
 if(form.id==='eds-bind-form'){const ids=new FormData(form).getAll('end_user_ids');await send(edsPath('/desktops/'+encodeURIComponent(form.dataset.id)+'/users',form.dataset.region),'POST',{operation:data.operation,end_user_ids:ids});$('#modal').close();toast('EDS user access update was accepted.');return await render();}
 if(form.id==='eds-user-create-form'){await send(edsPath('/users'),'POST',{username:data.username,email:data.email,display_name:data.display_name,password:data.password,is_local_admin:!!data.is_local_admin});$('#modal').close();toast('EDS user creation was accepted.');return await render();}
 if(form.id==='eds-policy-form'){await send(edsPath('/desktops/'+encodeURIComponent(form.dataset.id)+'/policy',form.dataset.region),'POST',{policy_group_id:data.policy_group_id});$('#modal').close();toast('EDS policy change was accepted.');return await render();}
 if(form.id==='eds-maintenance-form'){if(!confirm(`${data.mode==='ENTER'?'Enter':'Exit'} maintenance mode for this desktop?`))return;await send(edsPath('/desktops/'+encodeURIComponent(form.dataset.id)+'/maintenance',form.dataset.region),'POST',{mode:data.mode});$('#modal').close();toast('Maintenance mode update was accepted.');return await render();}
 if(form.id==='eds-command-form'){const timeout=Number(data.timeout),response=await send(edsPath('/desktops/'+encodeURIComponent(form.dataset.id)+'/commands',form.dataset.region),'POST',{command:data.command,command_type:data.command_type,timeout,confirm:!!data.confirm}),invokeID=response.InvokeId||response.invoke_id;if(!invokeID)throw new Error('Alibaba accepted the command but did not return an invocation ID.');toast('Remote command accepted; waiting for output.');return await waitForEDSCommand(form.dataset.id,form.dataset.region,invokeID,timeout);}
 if(form.id==='eds-billing-form'){await send(edsPath('/desktops/'+encodeURIComponent(form.dataset.id)+'/billing',form.dataset.region),'POST',{charge_type:data.charge_type,period:Number(data.period),period_unit:data.period_unit,auto_pay:!!data.auto_pay,confirm_cost:!!data.confirm_cost});$('#modal').close();toast('Billing conversion request was accepted.');return await render();}
 let body=data,path='',method=form.dataset.id?'PUT':'POST';
 if(form.id==='account-form'){body={name:data.name,provider:data.provider,owner:data.owner,group_id:data.group_id?Number(data.group_id):null,regions:data.regions.split(',').map(s=>s.trim()).filter(Boolean)};if(data.access_key_id||data.secret_access_key||data.session_token)body.credentials={access_key_id:data.access_key_id,secret_access_key:data.secret_access_key,session_token:data.session_token};path='/accounts';}
 if(form.id==='group-form'){body={name:data.name,description:data.description,view_dashboard:!!data.view_dashboard,manage_cloud_accounts:!!data.manage_cloud_accounts,manage_group_members:!!data.manage_group_members};path='/groups';}
 if(form.id==='user-form')path='/users';
 if(form.id==='member-form'){path=`/groups/${form.dataset.id}/members/${data.user_id}`;body={role:data.role};method='PUT';}else if(form.dataset.id)path+='/'+form.dataset.id;
 if(form.id==='settings-form'){path='/settings';method='PUT';body={collector_interval_minutes:Number(data.collector_interval_minutes),audit_retention_days:Number(data.audit_retention_days)};}
 if(path){await send(path,method,body);if(form.id==='account-form')await initializeCloudContext();$('#modal').close();toast('Changes saved.');await render();}
 }catch(err){const target=$('#form-error',form);if(target)target.textContent=err.message;else toast(err.message);}finally{if(submit)submit.disabled=false;}
});
$('#login-form').addEventListener('submit',async e=>{e.preventDefault();const btn=$('button',e.target);btn.disabled=true;$('#login-error').textContent='';try{const data=Object.fromEntries(new FormData(e.target));const res=await send('/auth/login','POST',data);user=res.user;e.target.reset();showApp();}catch(err){$('#login-error').textContent=err.message;}finally{btn.disabled=false;}});
$('#signup-form').addEventListener('submit',async e=>{e.preventDefault();const btn=$('button',e.target);btn.disabled=true;$('#signup-error').textContent='';try{const data=Object.fromEntries(new FormData(e.target));const res=await send('/auth/signup','POST',data);user=res.user;e.target.reset();showApp();}catch(err){$('#signup-error').textContent=err.message;}finally{btn.disabled=false;}});
function authMode(mode){const signup=mode==='signup';$('#login-form').hidden=signup;$('#signup-form').hidden=!signup;$('#login-tab').classList.toggle('active',!signup);$('#signup-tab').classList.toggle('active',signup);(signup?$('#signup-form input'):$('#login-form input')).focus();}
$('#login-tab').addEventListener('click',()=>authMode('login'));
$('#signup-tab').addEventListener('click',()=>authMode('signup'));
$('#logout').addEventListener('click',async()=>{try{await send('/auth/logout','POST',{});showLogin();}catch(err){toast(err.message);}});
$('#account-context').addEventListener('change',e=>{selectedAccount=cloudAccounts.find(a=>String(a.id)===e.target.value)||null;localStorage.setItem('nexus.account.'+user.id,selectedAccount?String(selectedAccount.id):'');edsRegion=selectedAccount?preferredEDSRegion():'';edsRegions=[];edsQuery='';edsState='';edsBilling='';if((page==='eds'||page==='edsusers')&&selectedAccount?.provider!=='alibaba')location.hash='instances';renderProviderNavigation();query='';state='';region='';offset=0;render();});
$('#close-modal').addEventListener('click',()=>$('#modal').close());
$('#close-custom-modal').addEventListener('click',()=>$('#custom-modal').close());
window.addEventListener('hashchange',()=>{query='';state='';region='';offset=0;render();});
(async()=>{try{user=await api('/auth/me');showApp();}catch{showLogin();}})();
