'use strict';

// Documentation is data-driven so this information architecture can grow
// without coupling article content to portal routing or UI behavior.
window.NEXUS_DOCS = [
  {id:'getting-started',category:'Getting Started',title:'Start with Netriun Nexus',summary:'Create a verified workspace, add your team, and connect the first cloud.',steps:['Register with a unique email and verify it from the message sent by Nexus.','Sign in and open Cloud connections.','Connect a dedicated cloud identity and test it before saving.','Open a compute service to see the latest snapshot immediately while Nexus refreshes it in the background.'],notes:['Use a dedicated cloud identity. Never connect a root or personal administrator credential.']},
  {id:'team-members',category:'Getting Started',title:'Invite your team',summary:'A Community workspace includes its owner plus five members.',steps:['Open Team members and add a unique username and email.','The member verifies their email before signing in.','Create an access policy and add the member with a viewer, operator, or manager role.']},
  {id:'cloud-connect',category:'Cloud Connections',title:'Connect a cloud account',summary:'The connection wizard validates identity and compute access before saving.',steps:['Choose AWS, Alibaba Cloud, Microsoft Azure, or Google Cloud.','Enter a friendly name, optional owner, access policy, and optional region filters.','Enter the provider-specific credential.','Run Test connection, then save within ten minutes.'],notes:['Credentials are encrypted at rest and are never returned by the API.','A successful test is bound to the signed-in user, provider, and exact credential values, and is consumed when saved.']},
  {id:'cloud-aws',category:'Cloud Connections',title:'Amazon Web Services',summary:'Connect a dedicated IAM access key for EC2 inventory and lifecycle operations.',steps:['Create an IAM principal for Nexus.','Grant EC2 describe permissions for inventory.','Optionally grant StartInstances, StopInstances, and RebootInstances.','Enter the AccessKey ID, secret, and optional temporary session token.']},
  {id:'cloud-alibaba',category:'Cloud Connections',title:'Alibaba Cloud',summary:'Connect a RAM user for ECS and WUYING EDS.',steps:['Create a dedicated RAM user and AccessKey.','Apply the policy from docs/alibaba-policy.json.','Enter the AccessKey ID and secret.','After saving, select the account to expose EDS services.']},
  {id:'cloud-azure',category:'Cloud Connections',title:'Microsoft Azure',summary:'Use a Microsoft Entra service principal scoped to a subscription.',steps:['Register an Entra application and create its service principal.','Grant Reader for inventory or Virtual Machine Contributor for lifecycle actions.','Copy Tenant ID, Application Client ID, Client Secret, and Subscription ID.','Enter those values in the connection wizard and run the test.'],notes:['Client secrets expire. Record the expiration and rotate before it is reached.']},
  {id:'cloud-gcp',category:'Cloud Connections',title:'Google Cloud',summary:'Use a dedicated service-account JSON key scoped to one project.',steps:['Enable the Compute Engine API in the project.','Create a service account with Compute Viewer or Compute Instance Admin (v1).','Create and download a JSON key.','Enter the Project ID, paste the complete JSON key, and run the test.'],notes:['Service-account keys are long-lived secrets. Rotate and revoke unused keys.']},
  {id:'compute-overview',category:'Services',title:'Compute inventory',summary:'Fetch, search, filter, inspect, and operate compute instances across connected clouds.',steps:['Choose one cloud provider and select one or more accounts from that provider.','Open its compute service to display the latest snapshot and queue a background refresh.','Use list or visual mode, search, filters, sorting, and pagination without triggering another provider request.','Choose Refresh live when you need to explicitly queue another refresh.','Open a resource for provider-native live details.']},
  {id:'eds-desktops',category:'Services',title:'Alibaba EDS desktops',summary:'Manage WUYING desktops across available regions.',steps:['Select an Alibaba Cloud connection.','Choose a region or All available regions.','Create, renew, start, stop, and manage desktops.','Use remote command only on a running desktop and review its returned output.']},
  {id:'eds-users',category:'Services',title:'Alibaba EDS users',summary:'Create convenience users and manage desktop assignments across regions.',steps:['Select an Alibaba account and EDS Users.','Create the convenience user.','Open bound desktops for that user.','Bind or unbind desktops across available regions.']},
  {id:'access-groups',category:'Access Management',title:'Policies and account roles',summary:'Give each person or team the right role for each cloud account.',steps:['Open Access policies and review the effective user-by-account matrix.','Create teams and manage their viewer, operator, or manager memberships.','Choose Assign access and select a person or team, cloud account, and account role.','Use Viewer for read-only inventory, Operator for lifecycle actions, or Account Manager for connection administration.','Review the matrix again to confirm the effective result.'],notes:['The first explicit assignment safely converts effective legacy access for that account before the new policy becomes authoritative.','Workspace administrators retain access to every account in their workspace.']},
  {id:'single-sign-on',category:'Access Management',title:'OIDC and SAML single sign-on',summary:'Federate workspace identity while keeping cloud authorization inside Nexus.',steps:['Open Workspace settings and add an OIDC or SAML identity provider.','For OIDC, configure the exact callback URL; for SAML, import the generated SP metadata into the IdP.','Enable the provider and copy its direct sign-in URL or distribute the workspace SSO code.','Map exact IdP group values to Nexus teams and choose the membership role cap.','Confirm sign-in and effective cloud-account access before requiring SSO.'],notes:['The Workspace Owner always retains local break-glass login.','OIDC requires a verified email claim; SAML requires a persistent NameID.','SSO group synchronization never removes manual team memberships.']},
  {id:'audit-log',category:'Access Management',title:'Audit log',summary:'Review workspace changes and cloud-operation intent.',steps:['Open Audit log as a workspace administrator.','Search by action, username, or target.','Investigate failed and accepted cloud operations using their target resource.']},
  {id:'lifecycle',category:'Operations',title:'Start, stop, and reboot',summary:'Lifecycle actions use the permissions of the connected cloud identity.',steps:['Confirm the selected account and resource.','Submit the action from list, visual, or detail view.','Wait for the next collection to confirm the provider-observed state.'],notes:['Stopping resources can interrupt users and workloads.']},
  {id:'workspace-settings',category:'Operations',title:'Live inventory and retention',summary:'Compute pages remain responsive by showing the latest healthy snapshot while live collection runs in the background.',steps:['Open a compute service page to queue an asynchronous provider refresh.','Watch the refresh status above the inventory while continuing to use the page.','Use Refresh live to explicitly queue or join the current refresh.','Open Workspace settings to configure audit retention.'],notes:['A failed provider request does not erase the last successful snapshot.','Equivalent in-flight requests are coalesced and account/region concurrency is limited to protect provider APIs.']},
  {id:'connection-errors',category:'Troubleshooting',title:'Connection test failed',summary:'Check identity values, credential expiry, API enablement, and role scope.',steps:['Confirm every ID belongs to the same account, tenant, subscription, or project.','Check that the credential is active and not expired.','Verify compute API access and the minimum role.','Remove region filters temporarily and test again.']},
  {id:'sync-errors',category:'Troubleshooting',title:'Live refresh failed',summary:'A failed provider read preserves the last successful database snapshot.',steps:['Open the connection and run Test connection with a fresh credential if needed.','Verify provider API availability and permissions.','Return to the service page and choose Refresh live.','Use Audit log to identify the affected connection.']},
  {id:'email-errors',category:'Troubleshooting',title:'Verification email problems',summary:'Recover an unverified portal account without creating another workspace.',steps:['Check spam and mailbox filtering.','Return to Sign in and enter the registered email.','After the verification warning, choose Resend verification email.','Use only the newest link; verification links expire after 24 hours.']},
  {id:'api-reference',category:'Troubleshooting',title:'API reference',summary:'Use the versioned REST API for automation and diagnostics.',steps:['Open API reference in the portal.','Authenticate with a verified email to receive a 12-hour bearer token.','Follow the same access-policy boundaries used by the portal.','Use docs/openapi.json as the machine-readable contract.']}
];
