apiVersion: v2
name: netriun-nexus
description: Netriun Nexus multi-cloud orchestration control plane
type: application
version: 0.2.2
appVersion: "0.1.2"
home: https://netriun.com/products
icon: https://raw.githubusercontent.com/sahiiib/netriun-nexus/main/internal/app/web/logo.svg
sources:
  - https://github.com/sahiiib/netriun-nexus
maintainers:
  - name: Netriun
